### ISSUE TITLE
PluginException in IDEA

### ISSUE THREAD

**Issue by robsdedude** [albertoventurini/graphdb-intellij-plugin#92]
Using IntelliJ IDEA 2024.1 (Ultimate Edition) - build `#IU-241.14494.240`, I got the following error when starting the IDE with version 0.8.0 of this plugin installed.

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.albertoventurini.graphdbplugin.jetbrains.actions.execute.ExecuteAllAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.albertoventurini.jetbrains.graphdbplugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

**Comment by vexos-io** [comment]
same error with #IU-242.22855.74

**Comment by sergio-nunez-meneses** [comment]
Same error with PhpStorm 2024.2.3 (#PS-242.23339.16)

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.albertoventurini.graphdbplugin.jetbrains.ui.datasource.actions.RefreshDataSourcesAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.albertoventurini.jetbrains.graphdbplugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```
